create table chat
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message    varchar(255)                                                                               not null,
    room       integer,
    wallet_id  integer,
    created_at timestamp with time zone default now() not null
);

create function notify_chat() returns trigger
    language plpgsql
as
$$
BEGIN
    PERFORM pg_notify(
            'notify_chat',
            row_to_json(NEW)::text
        );
    RETURN NEW;
END;
$$;

create trigger chat_insert
    after insert
    on chat
    for each row
execute procedure notify_chat();

